### ISSUE TITLE
Documentations & Basic explanations

### ISSUE THREAD

**Issue by susemeee** [PopchainOrg/PopChain#1]
The source code of blockchain implementation does not have any documents.

I think it actually should need some basic explanations such as,
- How to compile the source code
- What is currently implemented 
- A TODOs and milestones to be implemented (related to roadmap on a whitepaper)

**Comment by pjc0247** [comment]
gd

**Comment by pbes0707** [comment]
@pjc0247 pjc, are you scam?

**Comment by arminsu7** [comment]
@susemeee We do have a list of plans and milestones, and it will posted here recently. Our technical team is developing the core modules, and expect to release a compilable version which contains all instructions in this month.
